### ISSUE TITLE
iOS will close server when user closing screen (in release mode)

### ISSUE THREAD

**Issue by xuexin** [Jaguar-dart/jaguar#117]
For my app, I making server listening app's lifecycle to restart.
Could this problem be resolved in jaguar?

**Comment by xuexin** [comment]
Yes, fixed by `restart` method
I just want to know whether it can be fixed more robust :-D

**Comment by tejainece** [comment]
`restart` looks fine and neat to me. Do you need more restart functionality?

**Comment by xuexin** [comment]
No, it enough.
But this issue will make other users confused, so I hope it could be resolved in jaguar.

**Comment by Yongle-Fu** [comment]
https://github.com/Jaguar-dart/jaguar/pull/152
