### ISSUE TITLE
Should we give Response a default utf-8 charset?

### ISSUE THREAD

**Issue by lvscar** [Jaguar-dart/jaguar#119]
In the [Response](https://github.com/Jaguar-dart/jaguar/blob/cbf7e034041268639c6ca2ec57563d37f6acd88d/jaguar/lib/src/http/response/response.dart#L21)object initializing process, If the response value contain some non-latin characters, at the same time the user didn't set the optional charset parameter to 'utf-8'.  The Jaguar server will just output an "empty" HTTP response ( content-length: 0 , empty HTTP body) without any error message displayed in terminal .

I found [there](https://github.com/AsyncHttpClient/async-http-client/issues/1439) have some related discussion and some information about standards. According to these linked standard webpages, we could set the default charset to utf-8 at least for JSON response safely.

**Comment by lvscar** [comment]
I have submitted a [PR](https://github.com/Jaguar-dart/jaguar/pull/120) to reveal the “silenced failure”.

**Comment by tejainece** [comment]
Will fix this.

**Comment by tejainece** [comment]
Which method do you use to write JSON response?

My plan is to set the default `charset` to `utf-8` only when the response is going to be JSON.

1. Mux HTTP methods:  `getJson`, `posJson`, etc.
2. Controller HTTP methods: `GetJson`, `PostJson`, etc
3. Response.json()

**Comment by tejainece** [comment]
It looks like you use `Response.json`, the other two methods already use `utf-8` by default.

**Comment by tejainece** [comment]
Try Jaguar `2.1.26`, it uses `utf-8` by default for `Response.json`.

Would this be enough?

**Comment by tejainece** [comment]
Try `Jaguar` `2.1.26`, it uses `utf-8` by default for `Response`.

**Comment by tejainece** [comment]
Let me know if it has fixed the problem.

**Comment by lvscar** [comment]
After upgrade to Jaguar 2.1.27. I confirm the issue is resolved!

**Comment by tejainece** [comment]
@lvscar Here is a video about various methods for JSON serialization using Jaguar: https://www.youtube.com/watch?v=zW_PTzmw2N0&t=12s

There is also `jaguar_serializer` package that generates serializersfor models: https://github.com/Jaguar-dart/jaguar_serializer/wiki

**Comment by lvscar** [comment]
New tricks learned!
 "ctx.bodyAsJson(convert: Func)"  &  "Map toJSON"  both very handy in common api getaway programming.
 Love Jaguar more~

**Comment by lvscar** [comment]
After upgrade to Jaguar 2.2.10 , I found the default utf-8 charset for Response & Response.json was missing.

**Comment by lvscar** [comment]
PR #123 submitted
