### ISSUE TITLE
Adding SSL for localhost within Flutter 

### ISSUE THREAD

**Issue by godslave05** [Jaguar-dart/jaguar#130]
I am adding SSL by this way but it's not working

` ByteData data = await rootBundle.load('assets/ssl/certificate.pem');
ByteData keyBytes = await rootBundle.load('assets/ssl/keys.pem');
SecurityContext security = SecurityContext();
security.usePrivateKeyBytes(keyBytes.buffer.asInt8List(), password: '123456');
security.setTrustedCertificatesBytes(data.buffer.asInt8List());
final server = Jaguar(port: 2723, securityContext: security);
server.addRoute(serveFlutterAssets());
await server.serve(logRequests: true);

// debug
server.log.onRecord.listen((r) => print(r));`
I am calling -- https:/localhost:2723/index.html
but it's not working.

Anything missing here ?

**Comment by tejainece** [comment]
Will be handled here: https://github.com/jaguar-examples/flutter_webview/issues/7
