### ISSUE TITLE
responseProcessor not called for staticFiles

### ISSUE THREAD

**Issue by PiN73** [Jaguar-dart/jaguar#140]
I want to override response mime type when serving static files.

Tried to use `responseProcessor`
```dart
final server = Jaguar();
server.staticFiles(
  '/static/*',
  'static',
  responseProcessor: (Context context, dynamic result) {
    print('INSIDE responseProcessor');
  },
);
await server.serve();
```

but when the files are requested, my callback isn't called.

Is it a bug in Jaguar or am I doing something wrong?

**Comment by PiN73** [comment]
Discovering https://github.com/Jaguar-dart/jaguar/pull/137 I found that overriding mime type is possible this way for now
```dart
final server = Jaguar();
server.staticFiles('/static/*', 'static');
server.after.add((ctx) {
  if (ctx.path.startsWith('/static/') && ctx.path.endsWith('.txt')) {
    // for example, when serving .txt files, set mime type to text/html
    ctx.response.headers.mimeType = MimeTypes.html;
  }
});
await server.serve();
```

**Comment by PiN73** [comment]
Anyway it would be good to know if `responseProcessor` should be called in my case

**Comment by tejainece** [comment]
@PiN73 `responseProcessor` is only called when you return a result from the route handler. Static file handler does not return result, it instead updates the `response` object.

Using `after` is the right way to go for this.

**Comment by PiN73** [comment]
@tejainece but then `responseProcessor` parameter inside `Jaguar@staticFiles` isn't consistent and shouldn't be present, should it?
