### ISSUE TITLE
Latest flutter dependencies

### ISSUE THREAD

**Issue by FelixYew** [Jaguar-dart/jaguar#143]
First of all nice package!
Can you upgrade to support flutter latest version of dependencies. Thank you.

**Comment by tejainece** [comment]
Hi,

Which package? Which versions?

**Comment by FelixYew** [comment]
crypto >= 3.0.0
mime >= 1.0.0

**Comment by tejainece** [comment]
Thanks! I will fix it in a day or two.

**Comment by tejainece** [comment]
Can you confirm that this has been fixed? Thanks.

**Comment by FelixYew** [comment]
Yes the issue has been fixed. Thanks!
