### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by nosmirck** [Jaguar-dart/jaguar#144]
I'm about to start a project where I'll use flutter for the app side of things, I'd like to keep Dart as the do-it-all language and I've been looking around for a Dart-based Server framework to write my backend (I know I can go with something like Shelf, but it is too bare bones).

I've been looking around and 2 other frameworks that were more popular are now dead (Angel and Aqueduct). No one is maintaining them and no plan to upgrade to null-safety.

This project has not been touched in over 8 months and as I checked it's not compatible with null-safety. Is this project also dead? what's the status of Jaguar?

Thanks in advance for your response and if anyone can recommend a substitute that works great, I'll take it!

**Comment by gokr** [comment]
I am in exactly the same situation, although I already have several Aqueduct based backends implemented which we now consider migrating to something else in the longer run. A bit unfortunate. We are looking at possibly abandoning the "one lang" idea and simply drop to Go lang for backend.

**Comment by tejainece** [comment]
I actively use it and maintain this project. If you find any suggestion, problem or bug, create an issue or PR here on github. I will work on it.

**Comment by gokr** [comment]
And you are in Stockholm :) that's cool. So... I will chat with you on Gitter and see where we decide to go from here.

**Comment by nosmirck** [comment]
@tejainece thank you! Any plans on upgrading to null safety? One of the reasons the other projects are abandoned is because they don't have plans on upgrading and/or upgrading would cost too much time.

**Comment by tejainece** [comment]
@nosmirck yes. I have already migrated and checkedin null safety for some projects. In about a week, the whole project should have been migrated to null safety.

**Comment by PiN73** [comment]
Do you need any contribution in null safety migration?

**Comment by dynaevdv** [comment]
> @nosmirck yes. I have already migrated and checkedin null safety for some projects. In about a week, the whole project should have been migrated to null safety.

Hi. Do u need some help for migrate to null-safety? Thank you very much for your amazing framework

**Comment by CodeDoctorDE** [comment]
Any updates to the state?

**Comment by Wissperwind** [comment]
So since Angel and Aqueduct are deprecated this is the only surviving Dart Server Framework at the moment, correct?
In that case, cool!! that there is a surviving one.

**Comment by CodeDoctorDE** [comment]
You can use shelf by google but it doesn't get frequency updates

**Comment by dynaevdv** [comment]
> So since Angel and Aqueduct are deprecated, this is the only surviving Dart Server Framework at the moment, correct?
> In that case, cool!! that there is a surviving one.

Jaguar seems like deprecated too :(

**Comment by CodeDoctorDE** [comment]
yeah, it needs to update. until it's finished, I use shelf

**Comment by tejainece** [comment]
@dynaevdv I am working on migrating to null safety. There are lot of dependencies needing upgrades too.

**Comment by CodeDoctorDE** [comment]
maybe you can create multiple branches to specify release (main branch) and preview (develop branch):

**Comment by CodeDoctorDE** [comment]
If anyone wants to get the new version:
```yaml
dependencies:
  jaguar:
    git: 
      url: git://github.com/Jaguar-dart/jaguar
      path: jaguar
```

It would be cool if you document the root README.md to explain every package in this repository

**Comment by Hexer10** [comment]
@tejainece I would able to help out in the migration process, but it would be great to have an issue to track the progress; I wouldn't want to do duplicate work on the same code

**Comment by dynaevdv** [comment]
@tejainece Yeah, we really want to help you. You can open new branch 'null-safety' for PR from us.

**Comment by tejainece** [comment]
@dynaevdv I have pushed null safety changes to master branch. There are no errors in the library itself and all direct dependencies are ported.

However, I am working on porting dev dependencies that are use in tests.

**Comment by tejainece** [comment]
@Hexer10 Here is the issue tracking null safety migration: https://github.com/Jaguar-dart/jaguar/issues/147

I will update the issue as we go.

**Comment by dynaevdv** [comment]
@tejainece Thank you very much. You are awesome!

**Comment by tejainece** [comment]
Null safe version of the Jaguar has been published to pub.dev as version `3.0.5`. Please report any issues you find. Thanks for the support!

**Comment by CodeDoctorDE** [comment]
The jaguar generator has no null safety support :/

**Comment by tejainece** [comment]
@CodeDoctorDE will fix it.
