### ISSUE TITLE
default queryparam for num equal to num

### ISSUE THREAD

**Issue by Kleak** [Jaguar-dart/jaguar#47]
```dart
@Get(path: '/ping')
String ping({num test: 1, int test1: 3, double test2: 4.0}) {
  return "pong $test $test1 $test2";
}
```

if you don't provide `test` in the query param `test` will be `null` instead of 1

**Comment by tejainece** [comment]
https://github.com/Jaguar-dart/jaguar/pull/51/commits/8b7ba7f5d3eff418eefc0c1f65cd5fec6d4d8494 adds testcases to reproduce this issue

**Comment by tejainece** [comment]
Fixed in https://github.com/Jaguar-dart/source_gen_help/commit/d5d427ee8d463eb136ad81a0868f1bdb3268ac46
